### ISSUE TITLE
Issue with Meross MSS210 plugs

### ISSUE THREAD

**Issue by pinityoufairy** [donavanbecker/homebridge-meross#138]
**Describe Your Problem:**
I have connected four Meross MSS210 plugs to the Meross app on iOS. I have sniffed the sign, timestamp and message ID using HTTP Catcher, and input the values. However, I get the following error in the log, and the switch is unresponsive.

**Logs:**
[18/12/2020, 15:56:47] [Bedside Lamp] calling getOnCharacteristicHandler for MSS210 at 192.168.1.158...
[18/12/2020, 15:56:47] [Bedside Lamp] Failed to POST to the Meross Device MSS210 at 192.168.1.158: Error: socket hang up
    at connResetException (internal/errors.js:617:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
}
[18/12/2020, 15:56:47] [Bedside Lamp] Retrieved status unsuccessfully.
[18/12/2020, 15:56:47] [Bedside Lamp] getOnCharacteristicHandler: false
[18/12/2020, 15:56:50] [Bedside Lamp] calling getOnCharacteristicHandler for MSS210 at 192.168.1.158...
[18/12/2020, 15:56:50] [Bedside Lamp] Failed to POST to the Meross Device MSS210 at 192.168.1.158: Error: socket hang up
    at connResetException (internal/errors.js:617:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
}
[18/12/2020, 15:56:50] [Bedside Lamp] Retrieved status unsuccessfully.
[18/12/2020, 15:56:50] [Bedside Lamp] getOnCharacteristicHandler: false

**Homebridge Config:**
{
    "bridge": {
        "name": "Homebridge ***",
        "username": "******",
        "port": *****,
        "pin": "***-***-***"
    },
    "accessories": [
        {
            "model": "MSS210",
            "name": "Bedside Lamp",
            "deviceUrl": "IP",
            "channel": 0,
            "messageId": "messageIDsnooped",
            "timestamp": *****TS,
            "sign": "****sign",
            "accessory": "Meross"
        }
    ],

**Comment by pinityoufairy** [comment]
When i trigger it on and off in homekit, homekit shows it turning on and off, but nothing actually happens to the switch. This error is reported in Homebridge logs:

[18/12/2020, 16:18:59] [Bedside Lamp] Failed to POST to the Meross Device MSS210 at 192.168.1.158: Error: connect EHOSTUNREACH 192.168.1.158:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -113,
  code: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.1.158',
  port: 80

**Comment by megabashment** [comment]
I got the same problem. I have the MS 310 working without a problem. Now adding new MS 210 for my christmas tree but it doesn´t work.




[24/12/2020, 14:49:50] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:49:51] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:49:54] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:49:59] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:49:59] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:49:59] xx 3] Set failed: false
[24/12/2020, 14:50:01] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:50:04] [Xiaomi Air Purifier] Polling properties
[24/12/2020, 14:50:05] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:50:06] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}
[24/12/2020, 14:50:06] [My FRITZ!Box] Updating guest WLAN
[24/12/2020, 14:50:11] [My FRITZ!Box] Updating thermostat 099950435403
[24/12/2020, 14:50:11] [My FRITZ!Box] Updating thermostat 099950436621
[24/12/2020, 14:50:31] xx 3] Failed to POST to the Meross Device MSS210 at 192.168 178.76: Error: connect ETIMEDOUT 192.0.0.168:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.0.0.168',
  port: 80
}

**Comment by tonystower** [comment]
Same here! With two MSS210 plugs. V frustrating, hope a solution can be found soon.

**Comment by donavanbecker** [comment]
See #151

**Comment by hectorkd** [comment]
My mss210 plugs are working perfectly in HomeKit but it shows they have an update available in the Meross app but when I go there it says they're all up to date?
![IMG_1514](https://user-images.githubusercontent.com/62357077/103774356-56309000-5024-11eb-82b8-55cdbd26e827.PNG)
![IMG_1516](https://user-images.githubusercontent.com/62357077/103774366-592b8080-5024-11eb-8c0c-b4761fdbaab2.PNG)

**Comment by pinityoufairy** [comment]
> My mss210 plugs are working perfectly in HomeKit
Worth pointing out there are at least 2 flavours of MSS201, one HomeKit natively enabled and one not. I would suggest you don’t connect your HK enabled MSS210 through home bridge, just connect straight to Home

**Comment by caseypugh** [comment]
I'm also getting this same exact error with MSG200 (smart garage opener, firmware 2.1.3 - hardware 2.0.0). When I first set this up, it was working great for a couple weeks. As of today it has completely stopped and getting this message non-stop in Homebridge logs

```sh
[1/26/2021, 4:36:13 PM] [Right Garage Door] Error: socket hang up
[1/26/2021, 4:36:14 PM] [Left Garage Door] Failed to POST to the Meross Device MSG200 at 192.168.0.162: Error: socket hang up
    at connResetException (internal/errors.js:607:14)
    at Socket.socketOnEnd (_http_client.js:493:23)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ECONNRESET'
}
[1/26/2021, 4:36:14 PM] [Left Garage Door] Error: socket hang up
[1/26/2021, 4:36:14 PM] [Right Garage Door] Failed to POST to the Meross Device MSG200 at 192.168.0.162: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read'
}
[1/26/2021, 4:36:14 PM] [Right Garage Door] Error: read ECONNRESET
```

My config
```json
"accessories": [
        {
            "model": "MSG200",
            "name": "Left Garage Door",
            "firmwareRevision": "2.1.3",
            "deviceUrl": "192.168.0.162",
            "channel": 1,
            "messageId": "09b...5ffb",
            "timestamp": 0,
            "sign": "bcdb...5a0d",
            "garageDoorOpeningTime": 13,
            "accessory": "Meross"
        },
        {
            "model": "MSG200",
            "name": "Right Garage Door",
            "firmwareRevision": "2.1.3",
            "deviceUrl": "192.168.0.162",
            "channel": 2,
            "messageId": "09b...5ffb",
            "timestamp": 0,
            "sign": "bcdb...5a0d",
            "garageDoorOpeningTime": 13,
            "accessory": "Meross"
        }
    ],
```

I wonder if it got a firmware update automatically and the API format has changed? I also tried to update the login credentials but that also did not work.
