### ISSUE TITLE
MSS210 not working

### ISSUE THREAD

**Issue by pparrilla** [donavanbecker/homebridge-meross#247]
**Describe Your Problem:**

I started today using homebridge. I was following the guide published, using HTTP Catcher and i obtained all the information needed, but my plug is not working.

**Logs:**

```
...
[3/13/2021, 5:08:45 PM] [homebridge-meross] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/13/2021, 5:08:45 PM] [homebridge-meross] Error: 
    at On.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2032:105)
    at On.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1909:14)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1454:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[3/13/2021, 5:08:45 PM] [Led] calling getOnCharacteristicHandler for MSS210 at 192.168.1.150...
[3/13/2021, 5:08:45 PM] [Led] getOnCharacteristicHandler: undefined
[3/13/2021, 5:08:45 PM] [homebridge-meross] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[3/13/2021, 5:08:45 PM] [homebridge-meross] Error: 
    at On.Characteristic.characteristicWarning (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2032:105)
    at On.Characteristic.validateUserInput (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1909:14)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1454:24)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[3/13/2021, 5:08:46 PM] [Led] calling setOnCharacteristicHandler for MSS210 at 192.168.1.150...
[3/13/2021, 5:08:46 PM] [Led] Set failed: false
[3/13/2021, 5:08:46 PM] [Led] setOnCharacteristicHandler: true
[3/13/2021, 5:08:46 PM] [Led] calling getOnCharacteristicHandler for MSS210 at 192.168.1.150...
[3/13/2021, 5:08:46 PM] [Led] getOnCharacteristicHandler: false
[3/13/2021, 5:08:47 PM] [Led] calling setOnCharacteristicHandler for MSS210 at 192.168.1.150...
```

**Homebridge Config:**

```json

***Read and Paste over this Text the Text Above^^^^^^

{
    "bridge": {
        "name": "Homebridge ----",
        "username": "---",
        "port": ---,
        "pin": "---"
    },
    "accessories": [
        {
            "model": "MSS210",
            "name": "Led",
            "deviceUrl": "---",
            "channel": 0,
            "messageId": "---",
            "timestamp": ---,
            "sign": "---",
            "accessory": "Meross"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        }
    ]
}
```

**Environment:**

* **Node.js Version**: v14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.3
* **Homebridge Meross Plugin Version**: v4.0.1
* **Homebridge Config UI X Plugin Version**: v4.40.0
* **Operating System**: Raspbian

**Comment by donavanbecker** [comment]
@pparrilla Please try v3.5.1 until 5.0.0 is released

**Comment by pparrilla** [comment]
Do you mean v3.4.1 of the plugin? Or the 3.5?

**Comment by pparrilla** [comment]
I noticed that the messageId, timestamp and sign is changing from one "On" to the next when i catch using HTTP catcher, can it be the bug?

**Comment by donavanbecker** [comment]
No you can re-use them.

**Comment by donavanbecker** [comment]
v5.0.0 is released
