### ISSUE TITLE
Cannot read property 'payload' of undefined

### ISSUE THREAD

**Issue by jogoyo** [donavanbecker/homebridge-meross#250]
**Describe The Bug:**

Upon updating to v5.0 and re-arranging config, the payload property cannot be read.

**To Reproduce:**

Update to v5.0 and check logs. In Home app, devices are moved to Default Room and not responding.

**Logs:**

[Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined

# **Environment:**

- **Node.js Version**: v14.16.0
- **NPM Version**: v6.14.11
- **Homebridge Version**: v1.3.3
- **Homebridge Meross Plugin Version**: v5.0
- **Homebridge Config UI X Plugin Version**: v4.40.0
- **Operating System**: Docker Alpine Linux (v3.12.4)

**Comment by donavanbecker** [comment]
@jogoyo Old accessory devices will be removed once you remove the accessory config. Also more logs will be needed and more info on your devices to be able to troubleshoot.

**Comment by jogoyo** [comment]
I'm using MSL-120 bulbs as mentioned in the logs. This is my homebridge log...

[3/15/2021, 1:06:34 AM] Loading 5 platforms...
[3/15/2021, 1:06:34 AM] [Config] Initializing config platform...
[3/15/2021, 1:06:34 AM] [Config] Running in Service Mode
[3/15/2021, 1:06:34 AM] [Camera FFmpeg] Initializing Camera-ffmpeg platform...
[3/15/2021, 1:06:34 AM] [Govee] Initializing Govee platform...
[3/15/2021, 1:06:34 AM] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[3/15/2021, 1:06:34 AM] [TplinkSmarthome] homebridge-tplink-smarthome v6.3.0, node v14.16.0, homebridge v1.3.3, api v2.7
[3/15/2021, 1:06:34 AM] [Meross] Initializing Meross platform...
[3/15/2021, 1:06:34 AM] [Meross] Using Default Refresh Rate: 5 seconds.
[3/15/2021, 1:06:34 AM] [Meross] Using Default Push Rate.
[3/15/2021, 1:06:34 AM] Loading 5 accessories...
[3/15/2021, 1:06:34 AM] [Plex] Initializing Plex accessory...
[3/15/2021, 1:06:34 AM] [Gaming PC] Initializing NetworkDevice accessory...
[3/15/2021, 1:06:34 AM] [Unraid Server] Initializing NetworkDevice accessory...
[3/15/2021, 1:06:34 AM] [Pi-hole] Initializing Pihole accessory...
[3/15/2021, 1:06:34 AM] [Joseph Roku TV] Initializing Roku accessory...
[3/15/2021, 1:06:34 AM] [Camera FFmpeg] [Eufy Cam] Configuring cached bridged accessory...
[3/15/2021, 1:06:34 AM] [TplinkSmarthome] Configuring cached accessory: [TP-LINK_Smart Plug_7063] UUID: 09b3154e-e940-4389-917d-ff8dcaf9ef2a deviceId: 8006B7381E534D4B547BEF269B6379391DAE71C5 
[3/15/2021, 1:06:34 AM] [Meross] Loading accessory from cache: Kitchen Light
[3/15/2021, 1:06:34 AM] [Meross] Loading accessory from cache: Bedroom Lamp
[3/15/2021, 1:06:34 AM] [Govee] [v2.13.1] initialised. Syncing with Govee.
[3/15/2021, 1:06:34 AM] [Meross] Restoring existing accessory from cache: Kitchen Light
[3/15/2021, 1:06:34 AM] [Meross] Restoring existing accessory from cache: Bedroom Lamp
Preparing Advertiser for 'HomeBoi D357' using ciao backend!
Setup Payload:
X-HM://00251VPKNPM1K
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 956-51-895 │     
    └────────────┘     
                       
Starting to advertise 'HomeBoi D357' using ciao backend!
[3/15/2021, 1:06:35 AM] Homebridge v1.3.3 (HomeBoi) is running on port 51893.
[3/15/2021, 1:06:35 AM] [Unraid Server] NetworkDevice "Unraid Server" (x) went from status "Offline" to "Online"
[3/15/2021, 1:06:35 AM] [Gaming PC] NetworkDevice "Gaming PC" (x) went from status "Offline" to "Online"
[3/15/2021, 1:06:35 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:35 AM] [TplinkSmarthome] New Device Online: [Living Room Lamp] plug [8006B7381E534D4B547BEF269B6379391DAE71C5] 192.168.13.30 9999
[3/15/2021, 1:06:35 AM] [TplinkSmarthome] Adding: [Living Room Lamp] plug [8006B7381E534D4B547BEF269B6379391DAE71C5]
[3/15/2021, 1:06:35 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:35 AM] [Govee] [Bed Lights] initialised with id 97:4D:A4:C1:38:BD:33:90.
[3/15/2021, 1:06:35 AM] [Govee] ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
[3/15/2021, 1:06:39 AM] [Camera FFmpeg] [Eufy Cam] [Snapshot] [rtsp @ 0x14dfd1033740] method SETUP failed: 461 Unsupported transport
[3/15/2021, 1:06:40 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:40 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:45 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:45 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:50 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:50 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:55 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:06:55 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:07:00 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:07:00 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:07:05 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:07:05 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:07:10 AM] [Meross] MSL-120 - Failed to refresh status of Kitchen Light: "Cannot read property 'payload' of undefined" undefined
[3/15/2021, 1:07:10 AM] [Meross] MSL-120 - Failed to refresh status of Bedroom Lamp: "Cannot read property 'payload' of undefined" undefined

And my config for v5.0...

{
    "name": "Meross",
    "devices": [
        {
            "model": "MSL-120",
            "name": "Kitchen Light",
            "firmwareRevision": "2.1.4",
            "deviceUrl": "192.168.13.12",
            "channel": 0,
            "messageId": "x",
            "timestamp": x,
            "sign": "x"
        },
        {
            "model": "MSL-120",
            "name": "Bedroom Lamp",
            "firmwareRevision": "2.1.4",
            "deviceUrl": "192.168.13.13",
            "channel": 0,
            "messageId": "x",
            "timestamp": x,
            "sign": "x"
        }
      ],
    "platform": "Meross"
}

**Comment by donavanbecker** [comment]
@jogoyo Can you publish http catcher of push from meross app?

**Comment by jogoyo** [comment]
HTTP catcher push params...

{
  "payload" : {
    "togglex" : {
      "onoff" : 1,
      "channel" : 0
    }
  },
  "header" : {
    "messageId" : "x",
    "method" : "SET",
    "from" : "http:\/\/192.168.13.13\/config",
    "timestamp" : x,
    "namespace" : "Appliance.Control.ToggleX",
    "uuid" : "2008277303984190827048e1e92e4b7d",
    "sign" : "x",
    "triggerSrc" : "iOSLocal",
    "payloadVersion" : 1
  }
}

Response...

{
  "header": {
    "messageId": "x",
    "namespace": "Appliance.Control.ToggleX",
    "method": "SETACK",
    "payloadVersion": 1,
    "from": "/appliance/2008277303984190827048e1e92e4b7d/publish",
    "timestamp": x,
    "timestampMs": 252,
    "sign": "x"
  },
  "payload": {}
}

Fyi- I am purposely adding the "x" to redact certain details.

**Comment by dakotaduff** [comment]
I'm getting the same for all of my dimmer switches.

`MSS560 - Failed to refresh status of Front Porch: "Cannot read property 'payload' of undefined" undefined`

My HTTP Catcher data is essentially the same as jogoyo's.

**Comment by rcoletti116** [comment]
+1 on this. MSL-120s. They worked fine in an earlier version of the beta, but the v5 and latest beta do not work. Here's a sample response from the GET /config with Payload.

`{
  "header": {
    "messageId": "x",
    "namespace": "Appliance.System.All",
    "method": "GETACK",
    "payloadVersion": 1,
    "from": "/appliance/2010237811739590831848e1e937310d/publish",
    "timestamp": x,
    "timestampMs": 442,
    "sign": "x"
  },
  "payload": {
    "all": {
      "system": {
        "hardware": {
          "type": "msl120d",
          "subType": "us",
          "version": "2.0.0",
          "chipType": "mt7682",
          "uuid": "x",
          "macAddress": "x"
        },
        "firmware": {
          "version": "2.1.4",
          "compileTime": "2020/04/30 14:26:09 GMT +08:00",
          "wifiMac": "18:90:88:33:f9:33",
          "innerIp": "10.0.0.152",
          "server": "mqtt.meross.com",
          "port": 443,
          "userId": x
        },
        "time": {
          "timestamp": 1615836495,
          "timezone": "America/New_York",
          "timeRule": [
            [1604210400, -18000, 0],
            [1615705200, -14400, 1],
            [1636264800, -18000, 0],
            [1647154800, -14400, 1],
            [1667714400, -18000, 0],
            [1678604400, -14400, 1],
            [1699164000, -18000, 0],
            [1710054000, -14400, 1],
            [1730613600, -18000, 0],
            [1741503600, -14400, 1],
            [1762063200, -18000, 0],
            [1772953200, -14400, 1],
            [1793512800, -18000, 0],
            [1805007600, -14400, 1],
            [1825567200, -18000, 0],
            [1836457200, -14400, 1],
            [1857016800, -18000, 0],
            [1867906800, -14400, 1],
            [1888466400, -18000, 0],
            [1899356400, -14400, 1]
          ]
        },
        "online": {
          "status": 1
        }
      },
      "digest": {
        "togglex": [{
          "channel": 0,
          "onoff": 1,
          "lmTime": 1615836493
        }],
        "triggerx": [],
        "timerx": [],
        "light": {
          "capacity": 6,
          "channel": 0,
          "rgb": 16711680,
          "temperature": 97,
          "luminance": 100,
          "transform": -1
        }
      }
    }
  }
}`

**Comment by donavanbecker** [comment]
@jogoyo and @rcoletti116 could you try the latest beta?

Beta: `v5.0.1-beta.0`

**Comment by rcoletti116** [comment]
Sure. Still no response for the device in HK, but now I get [Meross] MSL-120 - Failed to refresh status of Bulb1: "socket hang up" undefined

**Comment by jogoyo** [comment]
Can confirm with @rcoletti116 
[Meross] MSL-120 - Failed to refresh status of Test Light: "socket hang up" undefined

**Comment by DredgenJ** [comment]
+1 on @jogoyo’s original post problem. Lights are still fully controllable though from Homebridge UI, Siri, HomePod, and shortcuts, just not via the Home app as it reports them as not responding.
+1 on the latest beta error message
Was getting socket hang up error until I used a different credential from HTTP Catcher.
Still getting error: [Meross] MSL-120 - Failed to refresh status of East: “Cannot read property ‘payload’ of undefined” undefined

I actually wasn’t having problems with either version (4.0.x, 5.0, 5.0.1 beta) or getting this error until the circuit with the lights tripped March 17. Prior to that I’d been using v5.0, v4.0.1, and the 5.0.1 beta for a few days with no issue (save the slowing homebridge). After the circuit tripped, I had to re-pair the lights with WiFi, Homebridge, and Meross (which reported a firmware update I declined) and it’s not been working properly since. I get several differing credentials from HTTP Catcher.

**Comment by rcoletti116** [comment]
Very strange. I had noticed that I could control in the homebridge UI, but assumed since Home app said no response that Siri would also not work. I can now confirm that Siri can control the light.

**Comment by gileswells** [comment]
I have the same issue as @jogoyo where my error has the "socket hang up" undefined. Slightly different from the title of this issue about reading a property of something undefined. Here's my debug log on my bulb.

```
[19/03/2021, 11:28:37] [Meross] MSL-120 - Reading 192.168.1.123/status
[19/03/2021, 11:28:37] [Meross] MSL-120 Meeting Bulb - {"message":"socket hang up","name":"Error","stack":"Error: socket hang up\n    at connResetException (internal/errors.js:607:14)\n    at Socket.socketOnEnd (_http_client.js:493:23)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"http://192.168.1.123/config","method":"post","data":"{\"payload\":{},\"header\":{\"messageId\":\"99f9f42308a88426e05c80026ba1f337\",\"method\":\"GETACK\",\"from\":\"http://192.168.1.123/config\",\"namespace\":\"Appliance.System.All\",\"timestamp\":1611773257,\"sign\":\"[ACTUAL SIGN VALUE]\",\"payloadVersion\":1}}","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.21.1","Content-Length":246},"transformRequest":[null],"transformResponse":[null],"timeout":0,"responseType":"json","xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1},"code":"ECONNRESET"}
[19/03/2021, 11:28:37] [Meross] MSL-120 - Failed to refresh status of Meeting Bulb: "socket hang up" undefined
```

better formatting
```json
{
  "message":"socket hang up",
  "name":"Error",
  "stack":"Error: socket hang up\n    at connResetException (internal/errors.js:607:14)\n    at Socket.socketOnEnd (_http_client.js:493:23)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
  "config":{
    "url":"http://192.168.1.123/config",
    "method":"post",
    "data": "{\"payload\":{},\"header\":{\"messageId\":\"99f9f42308a88426e05c80026ba1f337\",\"method\":\"GETACK\",\"from\":\"http://192.168.1.123/config\",\"namespace\":\"Appliance.System.All\",\"timestamp\":1611773257,\"sign\":\"[ACTUAL SIGN VALUE]\",\"payloadVersion\":1}}",
    "headers":{
      "Accept":"application/json, text/plain, */*",
      "Content-Type":"application/json",
      "User-Agent":"axios/0.21.1",
      "Content-Length":246
    },
    "transformRequest":[
      null
    ],
    "transformResponse":[
      null
    ],
    "timeout":0,
    "responseType":"json",
    "xsrfCookieName":"XSRF-TOKEN",
    "xsrfHeaderName":"X-XSRF-TOKEN",
    "maxContentLength":-1,
    "maxBodyLength":-1
  },
  "code":"ECONNRESET"
}
```

and being an over achiever, here's the data property's json all formatted and pretty
```json
{
  "payload":{
    
  },
  "header":{
    "messageId":"99f9f42308a88426e05c80026ba1f337",
    "method":"GETACK",
    "from":"http://192.168.1.123/config",
    "namespace":"Appliance.System.All",
    "timestamp":1611773257,
    "sign":"[ACTUAL SIGN VALUE]",
    "payloadVersion":1
  }
}
```

| Device info | value |
| --- | --- |
| Model | `msl120d` |
| Firmware | `2.1.4` |
| Hardware | `2.0.0` |

**Comment by rcoletti116** [comment]
> my error has the "socket hang up" undefined

Yep, the latest version has this as the socket hangup error now, but it is affecting the same devices.

**Comment by jogoyo** [comment]
Do we know if this issue has been fixed in v5.0.1?

**Comment by rcoletti116** [comment]
> Do we know if this issue has been fixed in v5.0.1?

I've tested and no its not fixed.

**Comment by DredgenJ** [comment]
> Very strange. I had noticed that I could control in the homebridge UI, but assumed since Home app said no response that Siri would also not work. I can now confirm that Siri can control the light.

@rcoletti116 I actually would never have thought to check- friends in my clan on Xbox love yelling commands to my HomePod mini if I join before my headphones connect, somebody did it, my lights came on and I was befuddled.

@donavanbecker Latest version still shows socket hang up error, although the error is different sometimes. Can post logs in detail if necessary

**Comment by koryhutchison** [comment]
Yeah I'm having the same issue as well when updating to v5.0.0. I had to revert and go back to v4.0.1 in order for my switch to work again.

**Comment by donavanbecker** [comment]
thanks to @gileswells for a potential fix to this!

@koryhutchison @DredgenJ @rcoletti116 @jogoyo @dakotaduff can you test out the latest beta and let me know if this is fixed? then I will release v5.0.2

Beta: `5.0.2-beta.0`

**Comment by rcoletti116** [comment]
confirmed, it is fixed.

**Comment by donavanbecker** [comment]
v5.0.2 is released
