### ISSUE TITLE
MSS210 plug won't work anymore

### ISSUE THREAD

**Issue by hectorkd** [donavanbecker/homebridge-meross#292]
**Describe The Bug:**

The plugs were working on HOOBS before the update and now they wont show up. HOOBS also won't start up again if I have anything written within the devices section.

**Logs:**

```
22/06/2021, 16:54:55 TypeError: this.service.getCharacteristic(...).onSet is not a function
    at new Outlet (/home/hoobs/.hoobs/node_modules/homebridge-meross/dist/devices/outlets.js:39:14)
    at Meross.discoverDevices (/home/hoobs/.hoobs/node_modules/homebridge-meross/dist/platform.js:222:25)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-meross/dist/platform.js:65:18)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

***Read and Paste over this Text the Text Above^^^^^^
```

**Screenshots:**

<img width="1158" alt="Screenshot 2021-06-22 at 16 55 18" src="https://user-images.githubusercontent.com/62357077/122959735-05ff7d00-d37b-11eb-8cff-313e5e3d787b.png">

**Comment by bwp91** [comment]
Can you update to beta version of the plugin to see if this is still an issue?
