### ISSUE TITLE
MSL-120 cannot update device

### ISSUE THREAD

**Issue by PatDal81** [donavanbecker/homebridge-meross#331]
### What issue do you have? Please be as thorough and explicit as possible.
Unable to interface with MSL-120 device

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Latest version of Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Latest version

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
RPI

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
Latest

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSL-120

Getting this error when trying to interface with the device: 

```
[22/08/2021, 22:48:23] [Meross] [Lumière chambre] sending update failed as  at Object.<anonymous> (/usr/lib/node_modules/homebridge-meross/node_modules/p-queue/dist/index.js:8:22).
```

**Comment by bwp91** [comment]
Hi @PatDal81 

Do you get this error *every* time you control this device? Or sometimes?

And do any functions work like on/off, brightness, colour, colour temperature?

For some reason the request is taking longer than 9 seconds (the time limit on trying to control the device).

Do you have this device setup as cloud device or local device?

Thanks

**Comment by PatDal81** [comment]
Hi @bwp91 

I now get this error every time I interact with it.

Any attempt to interact with it (on/off, change color, change brightness) fails with a "No Response" error within the Home app.  

I've setup the solution with the Cloud setup.

Here to help if you need anything else to help you.

Thanks.

**Comment by bwp91** [comment]
Can you use the plugin settings to turn plugin debug on, restart plugin and show me the logs from attempting to control the device? 

Also, does the accessory in homekit update status if you control the device via the meross app?

**Comment by PatDal81** [comment]
Another detail - This device is located at my cottage and not where I'm located physically (shouldn't change anything but FYI).  I have other device using your plugin (namely  MSS110-2) that works fine.

**Comment by PatDal81** [comment]
Here are the logs with debugging ON (thought about cleaning the logs but maybe you need the other info)

[23/08/2021, 09:16:28] [Meross] [Lumière chambre] sending mqtt: {"header":{"from":"/app/726764-1a12b231665266d8c6f0477c0f2392d8/subscribe","messageId":"0d50f125f8c94a99608289a16b41c60f","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"fa9157f740e3fdd937ea9dab4a63a605","timestamp":1629724589},"payload":{}}.
[23/08/2021, 09:16:29] [Meross] [test 2] disabling power readings interval as Timeout at new module.exports.TimeoutError (/usr/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
[23/08/2021, 09:16:29] [Meross] [test] disabling power readings interval as Timeout at new module.exports.TimeoutError (/usr/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
[23/08/2021, 09:16:29] [Meross] [Prise 3] disabling power readings interval as Timeout at new module.exports.TimeoutError (/usr/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
[23/08/2021, 09:16:30] [Meross] [Prise 4] disabling power readings interval as Timeout at new module.exports.TimeoutError (/usr/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
[23/08/2021, 09:16:30] [Meross] [Lumière chambre] mqtt connection closed.
[23/08/2021, 09:16:30] [Meross] [Prise 3] mqtt connection closed.
[23/08/2021, 09:16:30] [Meross] [Prise 4] mqtt connection closed.
[23/08/2021, 09:16:31] [Meross] [test] mqtt connection closed.
[23/08/2021, 09:16:31] [Meross] [Lumière salon] mqtt connection closed.
[23/08/2021, 09:16:31] [Meross] [test 2] mqtt connection closed.
[23/08/2021, 09:16:32] [Meross] [Lumière chambre] failed to request status as Timeout at new module.exports.TimeoutError (/usr/lib/node_modules/homebridge-meross/node_modules/promise-timeout/index.js:44:16).
[23/08/2021, 09:16:35] [Meross] [Lumière chambre] sending update: {"header":{"from":"http://192.168.2.210/config","messageId":"pwq030peubglgi5x","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"fe987a45d2b491a8fd7b9afe633c28c7","timestamp":1629724595,"triggerSrc":"iOSLocal","uuid":"1912139811151690806848e1e91364e4"},"payload":{"togglex":{"onoff":0,"channel":0}}}.
[23/08/2021, 09:16:35] [Meross] [Lumière chambre] mqtt connection reconnecting.
[23/08/2021, 09:16:35] [Meross] [Prise 3] mqtt connection reconnecting.
[23/08/2021, 09:16:35] [Meross] [Prise 4] mqtt connection reconnecting.
[23/08/2021, 09:16:36] [Meross] [test] mqtt connection reconnecting.
[23/08/2021, 09:16:36] [Meross] [Lumière salon] mqtt connection reconnecting.
[23/08/2021, 09:16:36] [Meross] [test 2] mqtt connection reconnecting.
[23/08/2021, 09:16:36] [Meross] [Lumière chambre] mqtt subscribe complete.
[23/08/2021, 09:16:36] [Meross] [Prise 3] mqtt subscribe complete.
[23/08/2021, 09:16:36] [Meross] [Prise 4] mqtt subscribe complete.
[23/08/2021, 09:16:36] [Meross] [test] mqtt subscribe complete.
[23/08/2021, 09:16:36] [Meross] [Lumière salon] mqtt subscribe complete.
[23/08/2021, 09:16:36] [Meross] [test 2] mqtt subscribe complete.
[23/08/2021, 09:16:38] [Meross] [Lumière chambre] reverting to cloud control as connect EHOSTUNREACH 192.168.2.210:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16).
[23/08/2021, 09:16:38] [Meross] [Lumière chambre] sending mqtt: {"header":{"from":"/app/726764-1a12b231665266d8c6f0477c0f2392d8/subscribe","messageId":"c49fa1a9cf95a6c7f885361d39bc889d","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"8f2ca6b42e890f6ba837c30f7160d284","timestamp":1629724599},"payload":{"togglex":{"onoff":0,"channel":0}}}.
[23/08/2021, 09:16:41] [Meross] [Lumière chambre] mqtt connection closed.
[23/08/2021, 09:16:41] [Meross] [Prise 3] mqtt connection closed.
[23/08/2021, 09:16:41] [Meross] [test] mqtt connection closed.
[23/08/2021, 09:16:41] [Meross] [Lumière salon] mqtt connection closed.
[23/08/2021, 09:16:41] [Meross] [Prise 4] mqtt connection closed.
[23/08/2021, 09:16:41] [Meross] [test 2] mqtt connection closed.
[23/08/2021, 09:16:45] [Meross] [Lumière chambre] sending update failed as  at Object.<anonymous> (/usr/lib/node_modules/homebridge-meross/node_modules/p-queue/dist/index.js:8:22).

You just made me realize that I cannot access the device via the Meross app!  it says "Unreachable" but I haven't changed anything.  Could this be a bug from Meross?

**Comment by bwp91** [comment]
The connection is constantly being opened and closed... do you have more than one instance of homebridge running the plugin with the same account info?

Also do you have the hybrid mode turned on in the plugin settings?

**Comment by PatDal81** [comment]
Yes and yes!  I do have one instance at home to control my devices at home, and the same is true for my cottage (both running on RPi, same config) using the same account.  It used to work properly but stopped working since yesterday.  I did my tests while at was at the cottage but now since moved to my house - this is when the problems started.

Hybrid mode is turned ON.

**Comment by bwp91** [comment]
This is the issue. The cloud connections don't work with two instances logged into the same account... this is why they are constantly disconnecting and reconnecting... a connection at one instance disconnects the other.

You have a number of options...

---

1. Obtain your userkey and setup one of the instances with this instead of the username/password, and setup the devices to be controlled locally by configuring the IP

---

2. Only run one instance of the plugin, and turn off hybrid mode so all devices work through the cloud - this will then work for devices situated in both places

---

3. Setup a separate meross account for the devices at one location and configure the plugin with these new credentials

**Comment by PatDal81** [comment]
Interesting - but that wouldn't explain why I'm still able to control my other devices that uses the same plugin (MSS110-2) without any error?  Also, I was able to control the faulty device (located at the cottage, while I was there) but I'm unable to control it when at home.  So only me, physically changing location, would render it unavailable?

**Comment by bwp91** [comment]
Could the IP of the device have changed?

The specific error you got was `EHOSTUNREACH 192.168.2.210:80` which often means the device is disconnected from network or no device at this IP.

Could you setup the device with a device IP in the config to force the plugin to use local mode and avoid using a cloud connection?

**Comment by bwp91** [comment]
In hybrid mode, the plugin will use the last IP of the device reported by meross, but any change in IP might not be reported immediately

**Comment by PatDal81** [comment]
Those devices uses a static IP address so it shouldn't have any impact.  In HB, it initially shows the device as being ON, 30% brightness and red.  This is the last state in which it was.  Does it fetch this info on refresh or is it the latest state reported by Meross?

**Comment by bwp91** [comment]
Another thing, are you controlling the correct accessory for the homebridge instance?

If you have two instances, this means each device will be duplicated in homebridge (unless you have ignored devices)…

**Comment by PatDal81** [comment]
Yes I've made sure they show up at the right place.

Have you seen my last question?  Curious how it handles the status.

**Comment by bwp91** [comment]
Yes, sorry, I haven't really been answering your questions, I've been more determined to find out why the device isn't responding 😆

> So only me, physically changing location, would render it unavailable?

No, your physical location should have no effect on which devices work

> Does it fetch this info on refresh or is it the latest state reported by Meross?

When the plugin starts it will request the latest device status from meross (either cloud or locally, depending on the config). Then the polling will start, by default every 5 seconds for local devices and every 5 minutes for cloud devices. It's longer for cloud devices, since the plugin should receive real-time updates from meross when the status is changed. The idea of the cloud polling is really to detect any IP change so that if using the hybrid mode then the IP is up to date.

If a cloud device goes offline then meross will continue to report the last known status (on/off, brightness, etc). If a local device goes offline then obviously the plugin will not be able to obtain the latest status. Either way, HomeKit will continue to display the last known state of the device.

Is this what you were asking?

**Comment by PatDal81** [comment]
Yes, thank you for the detailed explanation! :)

At this point, is there anything else I can do to help you troubleshoot this issue?  

My hypothesis right now is that the device is offline (don't remember if I switched the switch on or off before leaving) and Meross is reporting a bad status?

**Comment by bwp91** [comment]
> Yes, thank you for the detailed explanation! :)
> 
> At this point, is there anything else I can do to help you troubleshoot this issue?
> 
> My hypothesis right now is that the device is offline (don't remember if I switched the switch on or off before leaving) and Meross is reporting a bad status?

If in doubt, I would go by what the meross app is reporting for the device.

If you put the plugin into debug mode, you can see the data that the plugin receives from meross on startup. The data might not make much sense, but if you want to post it here I can take a look. It will be the message for the device that starts with `incoming poll`.

**Comment by PatDal81** [comment]
Yeah that is what I thought, the Meross app is reporting the bulb as open, 30%, red but unavailable.  I'm starting to guess it's an Meross bug at this point.  

Interrestingly, I do not have a "incoming pool" line for the faulty device.  I have one line for all other Meross device but not the faulty MSL-120.  Does it help?

**Comment by bwp91** [comment]
Initially it will try to poll locally, but this seems to be failing, then will try polling over cloud, but this will only work if the mqtt connection is open. In your logs the other day:

```
[23/08/2021, 09:16:30] [Meross] [Lumière chambre] mqtt connection closed.
[23/08/2021, 09:16:38] [Meross] [Lumière chambre] reverting to cloud control as connect EHOSTUNREACH 192.168.2.210:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16).
[23/08/2021, 09:16:38] [Meross] [Lumière chambre] sending mqtt: {"header":{"from":"/app/726764-1a12b231665266d8c6f0477c0f2392d8/subscribe","messageId":"c49fa1a9cf95a6c7f885361d39bc889d","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"8f2ca6b42e890f6ba837c30f7160d284","timestamp":1629724599},"payload":{"togglex":{"onoff":0,"channel":0}}}.
[23/08/2021, 09:16:41] [Meross] [Lumière chambre] mqtt connection closed.
```

You can see here the plugin isn't getting a response from either connection mode.

So actually my comment about the `incoming poll` wasn't helpful in this case!

**Comment by PatDal81** [comment]
Tried disabling the plugin on the second instance of HB.  Now I don't have the "mqtt connection closed" thing but unfortunately, getting the same error when interacting with the switch:

[24/08/2021, 12:16:18] [Meross] [Lumière chambre] sending update failed as  at Object.<anonymous> (/usr/lib/node_modules/homebridge-meross/node_modules/p-queue/dist/index.js:8:22).

**Comment by bwp91** [comment]
This error will be more readable in the next version of the plugin, it’s basically a timeout when the plugin doesn’t receive a reply from the device.

I think it makes sense to assume the device is offline in this case.

**Comment by bwp91** [comment]
I would also really advise to not have both instances running with your credentials. Set one of them to full local mode with the user key instead

**Comment by PatDal81** [comment]
Alright so I followed your recommendation and created two separate accounts for both my home and cottage.  I've separated the configs and setup them up properly.  I've also installed the latest version of your plugin (with enhanced logging) but I'm getting the same problem, unfortunately:

[25/08/2021, 18:12:25] [Meross] [Lumière chambre] sending mqtt: {"header":{"from":"/app/726764-1a12b231665266d8c6f0477c0f2392d8/subscribe","messageId":"fd7273a28e6fcceb4ceb4e2ca482738e","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"6ea5efc5acef4ea55c60b17b5533c094","timestamp":1629929
[25/08/2021, 18:12:29] [Meross] [Lumière chambre] failed to request status as Promise timed out after 4000 milliseconds at Timeout._onTimeout (/usr/lib/node_modules/homebridge-meross/node_modules/p-timeout/index.js:39:64).

**Comment by bwp91** [comment]
If you’re still getting this error via the cloud, and it’s also not working through the meross app, and it’s also the only device that’s not working, then it’s highly likely the device maybe is turned off at the power?

**Comment by PatDal81** [comment]
I will update you during the weekend with the outcome - I'll do some more testing.

**Comment by PatDal81** [comment]
Update for you: The device was off-sync finally.  When I arrived, the device was on but not working.  I reopened it and it started flashing (as if it was not connected anymore) then reconnected automatically.  Now the device works properly with the plugin.  

You can close this issue, seem like it was an off-sync between the device and meross itself.  Thanks for your help and assistance on this.

**Comment by PatDal81** [comment]
Closing the issue.
