### ISSUE TITLE
Disabling cloud client as login failed

### ISSUE THREAD

**Issue by MartinJRS** [donavanbecker/homebridge-meross#415]
* What issue do you have? Please be as thorough and explicit as possible.
Hello and thanks for your support. Out of the sudden, after I have just updated Homebridge UI, your plugin seems to experience issues. Device is not responding anymore under HomeKit and the log shows results as provided below.

* Details of your setup.
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 69BC)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi, Node.js v16.14.2, Nem v8.5.5

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
homebridge-meross v7.10.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
Model mss425f, Firmware 2.1.8, Hardware 2.0.0

### Please paste any relevant logs below.
[14/04/2022, 16:32:15] [Meross] Initializing Meross platform...
[14/04/2022, 16:32:15] [Meross] Initialising plugin v7.10.0 | Node v16.14.2 | HB v1.4.0 | HAPNodeJS v0.10.0...
[14/04/2022, 16:32:15] [Meross] Plugin initialised. Setting up accessories....
[14/04/2022, 16:32:15] [Meross] Disabling cloud client as login failed - {"apiStatus":0,"sysStatus":0,"info":"","timeStamp":1649946735,"data":{"userid":"137654","email":"******.*****@**.***","key":"********************","token":"***************"}} at connectionHTTP.login (/usr/local/lib/node_modules/homebridge-meross/lib/connection/http.js:75:15).
[14/04/2022, 16:32:15] [Meross] ***** Disabling plugin. *****
[14/04/2022, 16:32:15] [Meross] ***** Neither of username and password nor user key has been configured. *****

**Comment by ShaunRoberts543** [comment]
I am getting same issue since upgrading to 4.43.0 Homebridge.  Will not connect any Meross devices.  This is the log:


[14/04/2022, 08:48:27] [Meross] Disabling cloud client as login failed - {"apiStatus":0,"sysStatus":0,"info":"","timeStamp":1649940507,"data":{"userid":"85xxxxx","email":"shaunroxxxxxx@gmail.com","key":"e19dd68xxxxxxxdebf895899e51","token":"69abxxxxxxxe308a21427bd4a4e36xxxxxxxxxxxxcbf"}} at connectionHTTP.login (/usr/local/lib/node_modules/homebridge-meross/lib/connection/http.js:75:15).
[14/04/2022, 08:48:27] [Meross] ***** Disabling plugin. *****
[14/04/2022, 08:48:27] [Meross] ***** Neither of username and password nor user key has been configured. *****

**Comment by romk1n** [comment]
same issue here, I think meross has changed something on their side.

**Comment by HarrySteff** [comment]
Same problem here…

**Comment by bwp91** [comment]
Can anyone try beta version of the plugin?

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

Thanks!

**Comment by daniel-crouch** [comment]
> Can anyone try beta version of the plugin?
> 
> https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
> 
> Thanks!

Worked for me :)

**Comment by bwp91** [comment]
Cool just released new version of the plugin! Meross seem to have changed some of their response values and it caused the plugin to stop working!

**Comment by AndreGT6** [comment]
Update works. 
Thank you!

**Comment by HarrySteff** [comment]
Wow! Thank you for your great work!!! Well done!

**Comment by romk1n** [comment]
👍 super fast hotfix!

**Comment by MartinJRS** [comment]
Oh wow, that was super fast work ... you are wonderful. It works just fine - Thank you so much.

**Comment by 45Matches** [comment]
What issue do you have? Please be as thorough and explicit as possible.
Just following on from the previous update v7.10.1, all of a sudden I have for the last two days had the connected devices still visible in HomeKit, but not working. See logs below. Seems like a cloud connection issue? I hadn't made any changes or updates for several weeks until today when I updated the plugin to 7.10.1. Error occurred while running 7.10.0 and 1.10.1. Using the recommendation Hybrid Control connection type.

Details of your setup.
Homebridge UI-X

Which version of Homebridge/HOOBS do you have?
Homebridge [v1.4.0]

Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi, Node.js v16.14.2

Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
homebridge-meross v7.10.1

Which Meross devices do you have that are causing issues? Please include product models if applicable.
Garage Door Opener

LOGS
[19/04/2022, 21:30:48] [Meross] Disabling cloud client as Invalid password at connectionHTTP.login (/usr/local/lib/node_modules/homebridge-meross/lib/connection/http.js:75:15).
[19/04/2022, 21:30:48] [Meross] ***** Disabling plugin. *****
[19/04/2022, 21:30:48] [Meross] ***** Neither of username and password nor user key has been configured. *****
