### ISSUE TITLE
probably not really a bug....

### ISSUE THREAD

**Issue by Thomas-2009** [donavanbecker/homebridge-meross#417]
Dear ben,

first let me thank you for your great work!

I just started to use homebridge and your meross plug in.
It was very easy to set this up - thanks you a lot for this easy workflow ;-)

I encountered one thing which I can´t understand:
when I switch on/off my SmartPlugs I have to wait round about 3 sec till the plug changes its state...
Doing this in the "original Memos app" the plug changes its state immediately.

Is it normal, or do I miss some settings?

btw: I have a very low power hardware (Raspberry Pi Zero ;-) )

But the hue Lamps change very quickly (nearly immediately)

Thanks for your answer

**Comment by bwp91** [comment]
Hi @Thomas-2009 

Glad it was easy to setup!

You should use the plugin settings to enable "Debug Logging", restart Homebridge, and then try to control one of the meross switches and can you post here the logs that appear in the homebridge log?

Thanks!

**Comment by Thomas-2009** [comment]
Hi Ben,
many thanks for your quick reply!
I did what you told :-) - please have a look.
I switched on one of my Plugs and off afterwards - you see a ~3-4 sec. delay there...

My Systemconfig is:
DietPi
Node.js Version: v16.14.2
Npm Version: v8.7.0

Attention:
My network is 192.168.178.xxx
but all HomeKit and other external gadgets (vacuum cleaner, oven, basically all HomeKit devices except AppleTV) are connected on a separate "Guest-Network" 192.168.189.xxx
The guests may not talk to the internal network - (and I don't want to change this)
This just for information - but I don't expect this is an issue, because the "direct" way with the meross-app works instantly...

Kind regards,
Thomas


**> Switch on:**

[4/23/2022, 2:29:55 PM] [Meross] [Plug Klavier] sending update: {"header":{"from":"http://192.168.189.8/config","messageId":"58ceku1sg4ds7fauitidvc8wezvh1r0e","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"a2e910207a40335c8938c64055cb5556","timestamp":1650720595,"triggerSrc":"iOSLocal","uuid":"2006281930552751851148e1e9217c6c"},"payload":{"togglex":{"onoff":1,"channel":0}}}.

[4/23/2022, 2:29:59 PM] [Meross] [Plug Klavier] reverting to cloud control as timeout of 4000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-meross/node_modules/axios/lib/core/createError.js:16:15).
[4/23/2022, 2:29:59 PM] [Meross] [Plug Klavier] sending mqtt: {"header":{"from":"/app/771641-387de9a154a4de2e6bd93a80783228e6/subscribe","messageId":"cb54e56dbd596a6b2b70243384375e0b","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"bc36776e3bdb99f07ca82b40bd58e037","timestamp":1650720599},"payload":{"togglex":{"onoff":1,"channel":0}}}.

[4/23/2022, 2:29:59 PM] [Meross] [Plug Klavier] current state [on].

[4/23/2022, 2:29:59 PM] [Meross] [Plug Klavier] incoming mqtt: {"header":{"timestampMs":364,"timestamp":1650720599,"sign":"7219a1c40efbc243e5a9cb00a6ac1809","payloadVersion":1,"namespace":"Appliance.Control.ToggleX","method":"PUSH","messageId":"6a7e59a5c848542edbe2c233c5b703de","from":"/appliance/2006281930552751851148e1e9217c6c/publish"},"payload":{"togglex":[{"onoff":1,"lmTime":1650720598,"channel":0}]}}.


**> Switch off:**

[4/23/2022, 2:30:02 PM] [Meross] [Plug Klavier] sending update: {"header":{"from":"http://192.168.189.8/config","messageId":"g2wi0kjb49roid414x1ezfxa5qov5e39","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"d60c6a21f1ba2b1cb194892227b24341","timestamp":1650720602,"triggerSrc":"iOSLocal","uuid":"2006281930552751851148e1e9217c6c"},"payload":{"togglex":{"onoff":0,"channel":0}}}.

[4/23/2022, 2:30:06 PM] [Meross] [Plug Klavier] reverting to cloud control as timeout of 4000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-meross/node_modules/axios/lib/core/createError.js:16:15).

[4/23/2022, 2:30:06 PM] [Meross] [Plug Klavier] sending mqtt: {"header":{"from":"/app/771641-387de9a154a4de2e6bd93a80783228e6/subscribe","messageId":"cd272610a79a36b0db521112909c657c","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"400d65cea1f883945ba60fb6bda16431","timestamp":1650720607},"payload":{"togglex":{"onoff":0,"channel":0}}}.

[4/23/2022, 2:30:06 PM] [Meross] [Plug Klavier] current state [off].

[4/23/2022, 2:30:07 PM] [Meross] [Plug Klavier] incoming mqtt: {"header":{"timestampMs":616,"timestamp":1650720606,"sign":"6c734b4152a350d902740e9c899673e6","payloadVersion":1,"namespace":"Appliance.Control.ToggleX","method":"PUSH","messageId":"c444c146c921dd60d74e90f8167258d5","from":"/appliance/2006281930552751851148e1e9217c6c/publish"},"payload":{"togglex":[{"onoff":0,"lmTime":1650720606,"channel":0}]}}.

**Comment by bwp91** [comment]
I would recommend in the plugin settings changing the "Connection Type" to "Force Cloud Control".

This should avoid the 3|4 second delay when controlling devices :)

**Comment by Thomas-2009** [comment]
Hi Ben,

your tip was just right!!
This works like charm. 

Thank you very much for your time and quick response and keep coding as I can‘t do this ;-)

Cheers,
Thomas

**Comment by bwp91** [comment]
Glad you got it working!

If you were to set up a homebridge instance on your guest network, with the meross plugin you could control them via local control, and then in fact block the devices from the internet if you wanted to. although if you did this then they most probably wouldn’t work from the meross app

**Comment by Thomas-2009** [comment]
Thanks for your hint!
This will be the probably a little project for a rainy weekend for me :-)
