### ISSUE TITLE
MSS810 HomeKit version not being ignored despite  "ignoreHKNative": true

### ISSUE THREAD

**Issue by bvz-06** [donavanbecker/homebridge-meross#478]
### What issue do you have? Please be as thorough and explicit as possible.
I have a mix of Meross devices, two Homekit compatible, others not. I have enabled "ignoreHKNative": true.
Meross Homekit Native devices are ignored by Hoobs, except the MSS810.
The MSS810 is definitively the model with native HomeKit support as you can see in the debug los below.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
* HOOBS

* Which version of Homebridge/HOOBS do you have?
V4.2.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
V8.4.0

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSS810

### Please paste any relevant logs below.

The MSS810 has the name "Entree exterieur"

```
1/9/2023, 11:59:52 AMMeross Bridge starting
1/9/2023, 11:59:59 AMMeross BridgeLoaded plugin 'homebridge-meross'
1/9/2023, 11:59:59 AMMeross BridgeLoading 1 platforms...
1/9/2023, 11:59:59 AMMeross BridgeMerossInitialising plugin v8.4.0 | System linux | Node v16.18.1 | HB v1.5.0 | HAPNodeJS v0.10.2...
1/9/2023, 11:59:59 AMMeross BridgeMerossPlugin initialised. Setting up accessories....
1/9/2023, 11:59:59 AMMeross BridgeBridge is running on port 51836.
1/9/2023, 12:00:00 PMMeross BridgeMerossWARNINGMeross Key: 6a85217279671d1942c473084074709e
1/9/2023, 12:00:00 PMMeross BridgeMeross[Terrasse] not initialising cloud device as matched as HomeKit native model.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Entree extérieur] sending update: {"header":{"from":"http://192.168.1.65/config","messageId":"nyg977vn4b0t31j5cf34njtpl2pc6cg7","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"90cde6ac1ce835f655e1aae2425195ad","timestamp":1673262000,"triggerSrc":"iOSLocal","uuid":"2208251452147458180148e1e9a49e5f"},"payload":{}}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Entree extérieur] initialising with options {"connection":"hybrid","inUsePowerThreshold":0,"logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Entree extérieur] initialised with id [2208251452147458180148e1e9a49e5f].
1/9/2023, 12:00:00 PMMeross BridgeMeross[Entree extérieur] json debug info: {"uuid":"2208251452147458180148e1e9a49e5f","onlineStatus":1,"devName":"Entree extérieur","devIconId":"device_mss810_un","bindTime":1668439639,"deviceType":"mss810","subType":"un","channels":[{}],"region":"eu","fmwareVersion":"7.1.12","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"7.1.12","hbDeviceId":"2208251452147458180148e1e9a49e5f","model":"MSS810"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[X-Mas] sending update: {"header":{"from":"http://192.168.1.40/config","messageId":"zud09mw74zv5ipu6ounabj68v99qs31z","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"7efb3b51a3b4a3674de264c5f1c01e6d","timestamp":1673262000,"triggerSrc":"iOSLocal","uuid":"2109135851731051856948e1e976c63f"},"payload":{}}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[X-Mas] initialising with options {"connection":"hybrid","inUsePowerThreshold":0,"logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[X-Mas] initialised with id [2109135851731051856948e1e976c63f].
1/9/2023, 12:00:00 PMMeross BridgeMeross[X-Mas] json debug info: {"uuid":"2109135851731051856948e1e976c63f","onlineStatus":1,"devName":"X-Mas","devIconId":"device023_fr","bindTime":1644070228,"deviceType":"mss210","subType":"fr","channels":[{}],"region":"eu","fmwareVersion":"7.2.15","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"7.2.15","hbDeviceId":"2109135851731051856948e1e976c63f","model":"MSS210"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Garage] sending update: {"header":{"from":"http://192.168.1.37/config","messageId":"qzfu1yau0telaop4v4frko9dbo05ewcs","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"792106c00b4df21fbc9f74c26dfa5c95","timestamp":1673262000,"triggerSrc":"iOSLocal","uuid":"1909276119997990803048e1e952f6f9"},"payload":{}}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Garage] initialising with options {"connection":"hybrid","garageDoorOpeningTime":20,"logging":"debug"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Garage] initialised with id [1909276119997990803048e1e952f6f9].
1/9/2023, 12:00:00 PMMeross BridgeMeross[Garage] json debug info: {"uuid":"1909276119997990803048e1e952f6f9","onlineStatus":1,"devName":"Garage","devIconId":"device039_un","bindTime":1626093346,"deviceType":"msg100","subType":"us","channels":[{}],"region":"eu","fmwareVersion":"3.2.7","hdwareVersion":"3.5.0","userDevIcon":"","iconType":1,"cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"3.2.7","hbDeviceId":"1909276119997990803048e1e952f6f9","model":"MSG100"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[light] sending update: {"header":{"from":"http://192.168.1.11/config","messageId":"602enwpq7msdb2fu4qk6xzsh0yfkfhka","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"b3475590d723ef30bcdfb1f0dd07a70e","timestamp":1673262000,"triggerSrc":"iOSLocal","uuid":"1912182810496725580748e1e913f379"},"payload":{}}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[light] initialising with options {"connection":"hybrid","inUsePowerThreshold":0,"logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[light] initialised with id [1912182810496725580748e1e913f379].
1/9/2023, 12:00:00 PMMeross BridgeMeross[light] json debug info: {"uuid":"1912182810496725580748e1e913f379","onlineStatus":1,"devName":"light","devIconId":"device056_eu","bindTime":1595681661,"deviceType":"mss510x","subType":"eu","channels":[{}],"region":"eu","fmwareVersion":"3.2.2","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"3.2.2","hbDeviceId":"1912182810496725580748e1e913f379","model":"MSS510X"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Gate] sending update: {"header":{"from":"http://192.168.1.71/config","messageId":"kk37a8wnl8g04utsb4a9m4z5oiz6gj28","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"6b5605b646f8fec3917e030a5e7d497b","timestamp":1673262000,"triggerSrc":"iOSLocal","uuid":"1911085827278590804648e1e9111835"},"payload":{}}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Gate] initialising with options {"connection":"hybrid","garageDoorOpeningTime":20,"logging":"debug"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[Gate] initialised with id [1911085827278590804648e1e9111835].
1/9/2023, 12:00:00 PMMeross BridgeMeross[Gate] json debug info: {"uuid":"1911085827278590804648e1e9111835","onlineStatus":1,"devName":"Gate","devIconId":"device039_un","bindTime":1595081148,"deviceType":"msg100","subType":"us","channels":[{}],"region":"eu","fmwareVersion":"3.2.7","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"3.2.7","hbDeviceId":"1911085827278590804648e1e9111835","model":"MSG100"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[LAB] sending update: {"header":{"from":"http://192.168.1.44/config","messageId":"jo40wmobk58d4w7j948uexn5eznxspea","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"cf4aec570ff6f74957001906ecbe3f86","timestamp":1673262000,"triggerSrc":"iOSLocal","uuid":"1911298577018390805548e1e912223b"},"payload":{}}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[LAB] initialising with options {"connection":"hybrid","logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[branch] initialising with options {"connection":"hybrid","logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[7010] initialising with options {"connection":"hybrid","logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:00 PMMeross BridgeMeross[9004] initialising with options {"connection":"hybrid","logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[6200] initialising with options {"connection":"hybrid","logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[USB] initialising with options {"connection":"hybrid","logging":"debug","showAs":"switch"}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[LAB] initialised with id [1911298577018390805548e1e912223b].
1/9/2023, 12:00:01 PMMeross BridgeMeross[LAB] json debug info: {"uuid":"1911298577018390805548e1e912223b","onlineStatus":1,"devName":"LAB","devIconId":"device035_eu","bindTime":1584803329,"deviceType":"mss425f","subType":"eu","channels":[{},{"type":"Switch","devName":"branch","devIconId":"device001"},{"type":"Switch","devName":"7010","devIconId":"device001"},{"type":"Switch","devName":"9004","devIconId":"device001"},{"type":"Switch","devName":"6200","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"eu","fmwareVersion":"3.1.2","hdwareVersion":"3.0.0","userDevIcon":"","iconType":1,"cluster":2,"domain":"mqtt-eu-2.meross.com","reservedDomain":"mqtt-eu-2.meross.com","firmware":"3.1.2","hbDeviceId":"1911298577018390805548e1e912223b","model":"MSS425F"}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[light] incoming poll: {"header":{"messageId":"602enwpq7msdb2fu4qk6xzsh0yfkfhka","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/1912182810496725580748e1e913f379/publish","timestamp":1673262001,"timestampMs":327,"sign":"1938961134e92379afc5146b80788fbd"},"payload":{"all":{"system":{"hardware":{"type":"mss510x","subType":"us","version":"3.0.0","chipType":"mt7682","uuid":"1912182810496725580748e1e913f379","macAddress":"48:e1:e9:13:f3:79"},"firmware":{"version":"3.2.2","compileTime":"2021/09/15 14:22:44 GMT +08:00","encrypt":1,"wifiMac":"9c:8c:d8:15:5c:01","innerIp":"192.168.1.11","server":"mqtt-eu-2.meross.com","port":443,"userId":555487},"time":{"timestamp":1673262001,"timezone":"Europe/Paris","timeRule":[[1585443600,7200,1],[1603587600,3600,0],[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":1670881297}],"triggerx":[],"timerx":[]}}}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[light] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[light] sending update: {"header":{"from":"http://192.168.1.11/config","messageId":"7ysgjfsts2wbt8tyzf67oegkwgin2hzf","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"e87faae08fa0545958a66c49852b3dbd","timestamp":1673262001,"triggerSrc":"iOSLocal","uuid":"1912182810496725580748e1e913f379"},"payload":{}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[Garage] incoming poll: {"header":{"messageId":"qzfu1yau0telaop4v4frko9dbo05ewcs","namespace":"Appliance.System.All","triggerSrc":"iOSLocal","method":"GETACK","payloadVersion":1,"from":"/appliance/1909276119997990803048e1e952f6f9/publish","timestamp":1673262000,"timestampMs":792,"sign":"792106c00b4df21fbc9f74c26dfa5c95"},"payload":{"all":{"system":{"hardware":{"type":"msg100","subType":"us","version":"3.5.0","chipType":"mt7682","uuid":"1909276119997990803048e1e952f6f9","macAddress":"48:e1:e9:52:f6:f9"},"firmware":{"version":"3.2.7","compileTime":"2022/08/30 12:14:18 GMT +08:00","encrypt":1,"wifiMac":"f0:61:c0:2e:98:00","innerIp":"192.168.1.37","server":"mqtt-eu-2.meross.com","port":443,"userId":555487},"time":{"timestamp":1673262000,"timezone":"Europe/Paris","timeRule":[[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1],[1919293200,3600,0]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":0}],"triggerx":[{"channel":0,"id":"1111111111111111","count":1}],"timerx":[],"garageDoor":[{"channel":0,"open":0,"lmTime":1673260110}]}}}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[Garage] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[Gate] incoming poll: {"header":{"messageId":"kk37a8wnl8g04utsb4a9m4z5oiz6gj28","namespace":"Appliance.System.All","triggerSrc":"iOSLocal","method":"GETACK","payloadVersion":1,"from":"/appliance/1911085827278590804648e1e9111835/publish","timestamp":1673262001,"timestampMs":279,"sign":"3dc358a6e7ad30ff261122c3d462afca"},"payload":{"all":{"system":{"hardware":{"type":"msg100","subType":"us","version":"3.5.0","chipType":"mt7682","uuid":"1911085827278590804648e1e9111835","macAddress":"48:e1:e9:11:18:35"},"firmware":{"version":"3.2.7","compileTime":"2022/08/30 12:14:18 GMT +08:00","encrypt":1,"wifiMac":"9c:8c:d8:15:5c:01","innerIp":"192.168.1.71","server":"mqtt-eu-2.meross.com","port":443,"userId":555487},"time":{"timestamp":1673262001,"timezone":"Europe/Paris","timeRule":[[1585443600,7200,1],[1603587600,3600,0],[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":0}],"triggerx":[{"channel":0,"id":"1111111111111111","count":2}],"timerx":[{"channel":0,"id":"1111111111111111","count":1}],"garageDoor":[{"channel":0,"open":1,"lmTime":1673258554}]}}}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[Gate] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[X-Mas] incoming poll: {"header":{"messageId":"zud09mw74zv5ipu6ounabj68v99qs31z","namespace":"Appliance.System.All","triggerSrc":"iOSLocal","method":"GETACK","payloadVersion":1,"from":"/appliance/2109135851731051856948e1e976c63f/publish","uuid":"2109135851731051856948e1e976c63f","timestamp":1673262000,"timestampMs":583,"sign":"7efb3b51a3b4a3674de264c5f1c01e6d"},"payload":{"all":{"system":{"hardware":{"type":"mss210","subType":"un","version":"7.0.0","chipType":"rtl8710cm","uuid":"2109135851731051856948e1e976c63f","macAddress":"48:e1:e9:76:c6:3f"},"firmware":{"version":"7.2.15","homekitVersion":"4.1","compileTime":"2022/08/23-15:39:35","encrypt":1,"wifiMac":"9c:8c:d8:15:5c:01","innerIp":"192.168.1.40","server":"mqtt-eu-2.meross.com","port":443,"userId":555487},"time":{"timestamp":1673262000,"timezone":"Europe/Paris","timeRule":[[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1],[1919293200,3600,0],[1932598800,7200,1],[1950742800,3600,0],[1964048400,7200,1]]},"online":{"status":1,"bindId":"3iEV7pFsHAcpTOGd","who":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":1673261959}],"triggerx":[{"channel":0,"id":"554c7e69154e0333","count":8}],"timerx":[{"channel":0,"id":"24ea43897db4abcc","count":9},{"channel":0,"id":"36d037e3b799063c","count":4}]}}}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[X-Mas] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[X-Mas] sending update: {"header":{"from":"http://192.168.1.40/config","messageId":"1fdsb67sx46dhs3umj8dm8tdw8nga5te","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"b151f0e39505bdf91af331d2d5ec8002","timestamp":1673262001,"triggerSrc":"iOSLocal","uuid":"2109135851731051856948e1e976c63f"},"payload":{}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[Entree extérieur] incoming poll: {"header":{"messageId":"nyg977vn4b0t31j5cf34njtpl2pc6cg7","namespace":"Appliance.System.All","triggerSrc":"iOSLocal","method":"GETACK","payloadVersion":1,"from":"/appliance/2208251452147458180148e1e9a49e5f/publish","uuid":"2208251452147458180148e1e9a49e5f","timestamp":1673262001,"timestampMs":889,"sign":"138e3c7544429895feb1d99e5458a73d"},"payload":{"all":{"system":{"hardware":{"type":"mss810","subType":"un","version":"7.0.0","chipType":"rtl8710cm","uuid":"2208251452147458180148e1e9a49e5f","macAddress":"48:e1:e9:a4:9e:5f"},"firmware":{"version":"7.1.12","homekitVersion":"4.1","compileTime":"2022/05/19-14:41:03","encrypt":1,"wifiMac":"9c:8c:d8:15:5c:01","innerIp":"192.168.1.65","server":"mqtt-eu-2.meross.com","port":443,"userId":555487},"time":{"timestamp":1673262001,"timezone":"Europe/Paris","timeRule":[[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1],[1919293200,3600,0],[1932598800,7200,1]]},"online":{"status":1,"bindId":"StbTt0ECV9sqTHYB","who":1}},"digest":{"togglex":[{"channel":0,"onoff":0,"lmTime":1673202804}],"triggerx":[],"timerx":[]}}}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[Entree extérieur] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[Entree extérieur] sending update: {"header":{"from":"http://192.168.1.65/config","messageId":"iuawtuisjucqiux30t7ccucrxd658w73","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"0f248c3c681a3e085fff5f265fac5712","timestamp":1673262001,"triggerSrc":"iOSLocal","uuid":"2208251452147458180148e1e9a49e5f"},"payload":{}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[LAB] incoming poll: {"header":{"messageId":"jo40wmobk58d4w7j948uexn5eznxspea","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/1911298577018390805548e1e912223b/publish","timestamp":1673262001,"timestampMs":479,"sign":"69e790fdbb300d6831a88da43db1f2c7"},"payload":{"all":{"system":{"hardware":{"type":"mss425f","subType":"us","version":"3.0.0","chipType":"mt7682","uuid":"1911298577018390805548e1e912223b","macAddress":"48:e1:e9:12:22:3b"},"firmware":{"version":"3.1.2","compileTime":"2019/09/17 09:16:42 GMT +08:00","wifiMac":"44:48:c1:26:ad:a1","innerIp":"192.168.1.44","server":"mqtt-eu-2.meross.com","port":443,"userId":555487},"time":{"timestamp":1673262001,"timezone":"Europe/Paris","timeRule":[[1572138000,3600,0],[1585443600,7200,1],[1603587600,3600,0],[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":1673260820},{"channel":1,"onoff":0,"lmTime":1672936051},{"channel":2,"onoff":1,"lmTime":1673260830},{"channel":3,"onoff":1,"lmTime":1673260831},{"channel":4,"onoff":1,"lmTime":1673260826},{"channel":5,"onoff":1,"lmTime":1673260820}],"triggerx":[],"timerx":[]}}}}.
1/9/2023, 12:00:01 PMMeross BridgeMeross[LAB] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[branch] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[7010] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[9004] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[6200] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[USB] has been reported [online].
1/9/2023, 12:00:01 PMMeross BridgeMeross[X-Mas] mqtt subscribe complete.
1/9/2023, 12:00:01 PMMeross BridgeMeross[Entree extérieur] mqtt subscribe complete.
1/9/2023, 12:00:01 PMMeross BridgeMeross[Gate] mqtt subscribe complete.
1/9/2023, 12:00:01 PMMeross BridgeMeross[light] mqtt subscribe complete.
1/9/2023, 12:00:01 PMMeross BridgeMeross[light] reverting to cloud control as socket hang up at Function.AxiosError.from (file:///var/lib/hoobs/merossbridge/node_modules/axios/lib/core/AxiosError.js:89:14).
1/9/2023, 12:00:01 PMMeross BridgeMeross[light] sending mqtt: {"header":{"from":"/app/555487-db2334c6ee0470c45592a0b9fa1ba3c2/subscribe","messageId":"4efaaf4bbbb49c8a987dff107fe24ebc","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"e7f52f121bed4e3fa5d487edc75980f6","timestamp":1673262002},"payload":{}}.
1/9/2023, 12:00:02 PMMeross BridgeMeross[Entree extérieur] reverting to cloud control as socket hang up at Function.AxiosError.from (file:///var/lib/hoobs/merossbridge/node_modules/axios/lib/core/AxiosError.js:89:14).
1/9/2023, 12:00:02 PMMeross BridgeMeross[Entree extérieur] sending mqtt: {"header":{"from":"/app/555487-10fb4f585c59391ca51bcb38d134895a/subscribe","messageId":"790a14d4a5c6e4d5d1216d6766b00ebc","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"4d454308a952a52c7180b83229b25e40","timestamp":1673262002},"payload":{}}.
1/9/2023, 12:00:02 PMMeross BridgeMeross[LAB] mqtt subscribe complete.
1/9/2023, 12:00:02 PMMeross BridgeMeross[Garage] mqtt subscribe complete.
1/9/2023, 12:00:02 PMMeross BridgeMeross[X-Mas] reverting to cloud control as socket hang up at Function.AxiosError.from (file:///var/lib/hoobs/merossbridge/node_modules/axios/lib/core/AxiosError.js:89:14).
1/9/2023, 12:00:02 PMMeross BridgeMeross[X-Mas] sending mqtt: {"header":{"from":"/app/555487-cea02f42df80bab39138f28b621bb77e/subscribe","messageId":"22bce8b0145e56b18b143edbc64d5d0c","method":"GET","namespace":"Appliance.Control.Electricity","payloadVersion":1,"sign":"03a699836f016ffd38f1742b0a28e0d5","timestamp":1673262002},"payload":{}}.
1/9/2023, 12:00:03 PMMeross BridgeMeross✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
1/9/2023, 12:00:05 PMMeross BridgeMeross[light] disabling power readings interval as the request timed out.
1/9/2023, 12:00:06 PMMeross BridgeMeross[Entree extérieur] disabling power readings interval as the request timed out.
1/9/2023, 12:00:06 PMMeross BridgeMeross[X-Mas] disabling power readings interval as the request timed out.


```

**Comment by omulec** [comment]
Yeah, it's not on the list. Let's hope will be excluded as well as MSS510

**Comment by bwp91** [comment]
hi, please install new beta version :)
