### ISSUE TITLE
Is it possible to add MSS510X switches through this to force a local connection?

### ISSUE THREAD

**Issue by wild-a** [donavanbecker/homebridge-meross#494]
I have several MSS510X and MSS560 switches added to HomeKit (native HomeKit). However, I do not want them accessing the internet, but whenever I block internet access they stop working. I was hoping I can force a local connection with this plugin, is that possible? What are the steps to do that?

**Comment by wild-a** [comment]
This is the log

[2/24/2023, 6:18:27 PM] [Meross] [Dining Room Light] sending update: {"header":{"from":"http://192.168.4.89/config","messageId":"9cn0ka166uh7zobla2jxb6rshg3ley30","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"9526bb9f343add31520dd1f6b5dee306","timestamp":1677284307,"triggerSrc":"iOSLocal","uuid":"558586220305494"},"payload":{}}.
[2/24/2023, 6:18:27 PM] [Meross] [Dining Room Light] failed to request status as socket hang up at Function.AxiosError.from (file:///usr/lib/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:89:14).

**Comment by wild-a** [comment]
[2/24/2023, 6:28:50 PM] [Meross] [Dining Room Light] failed to request status as: socket hang up at Function.AxiosError.from (file:///usr/lib/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:89:14).

**Comment by bwp91** [comment]
Hi @wild-a 

when you block internet access from the devices are you sure they can still get access to the local network - ie - can get access to the plugin?
