### ISSUE TITLE
Error: Sending update failed as timeout of 9000ms exceeded

### ISSUE THREAD

**Issue by iTim314** [donavanbecker/homebridge-meross#512]
### What issue do you have? Please be as thorough and explicit as possible.
The garage door no longer responds to commands. Statuses eventually updated, but no commands are obeyed.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1, Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
v4.50.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Ubuntu LTS 22.04.2, Node v16.19.1

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
v9.0.1

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSG100HK

### Please paste any relevant logs below.

```
[3/15/2023, 12:58:40 PM] [Meross] [Garage Door] sending update failed as timeout of 9000ms exceeded at RedirectableRequest.handleRequestTimeout (file:///var/lib/homebridge/node_modules/homebridge-meross/node_modules/axios/lib/adapters/http.js:614:16).
```

**Comment by weekesey** [comment]
I have the same error, whether the command is obeyed or not is hit and miss.

Details of your setup.
Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
1, Homebridge UI-X

Which version of Homebridge do you have?
v1.6.0 (via Home Assistant) - homebridge-config-ui-x v4.50.2

Which platform do you run Homebridge?
Linux 6.1.0-0.deb11.5-amd64, Node v18.15.0

Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
v9.0.2

Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSG100

Error - [13/04/2023, 18:47:25] [Meross] [Garage Roller Left] sending update failed as timeout of 9000ms exceeded at RedirectableRequest.handleRequestTimeout (file:///usr/lib/node_modules/homebridge-meross/node_modules/axios/lib/adapters/http.js:614:16).

**Comment by bwp91** [comment]
Hi, do you (either of you!) have this device configured locally? or via the cloud (plugin default)

**Comment by weekesey** [comment]
Hi, not sure this answers the question but I have the connection type set to "Hybrid (Default)"

It has been configured the same was for 12 months plus, only had issues in the last month or so.

[14/04/2023, 11:19:20] [Meross] [Garage Roller Left] has been reported [online].
[14/04/2023, 11:21:22] [Meross] [Garage Roller Left] has been reported [offline].
[14/04/2023, 18:20:54] [Meross] [Garage Roller Left] sending update failed as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///usr/lib/node_modules/homebridge-meross/node_modules/p-queue/node_modules/p-timeout/index.js:79:64).
[15/04/2023, 11:25:10] [Meross] [Garage Roller Left] has been reported [online].
[15/04/2023, 11:30:10] [Meross] [Garage Roller Left] has been reported [offline].	

EDIT 16.4: I have set the connection type to "Force Local  Control (with configured IPs) to test.  So far since, every command has been obeyed.

**Comment by bwp91** [comment]
@iTim314 are you still experiencing this issue?

**Comment by iTim314** [comment]
Yes I am. I thought it was fixed with the v9.0.5 release as it worked for a day, then just stopped working all together with the same message.

**Comment by bwp91** [comment]
After this period of working - to not working with the plugin - if you then try to control with the meross app does it work?

**Comment by iTim314** [comment]
It doesn't, but that's to be expected given that I do not let the device reach the internet via firewall restrictions. I have suspected that the device — being unable to phone home — chokes and stops working. I was hoping I could use this device locally only. 

What's strange is that I still get status updates/notifcations over HomeKit almost instantly. But any command to open or close timesout.

**Comment by bwp91** [comment]
I’m keen to ask if your homebridge instance definitely has permission over the network to communicate with the device. but i guess this is a given if it works for ~24 hours then stops working

**Comment by iTim314** [comment]
It does. The IoT network (where the MSG100HK lives) can talk freely with the Homebridge VM.

**Comment by bwp91** [comment]
Okay great, and last thing i want to check (and sorry i have to check!) is that you are definitely using the homebridge plugin accessory of this device rather than the homekit native accessory itself?

**Comment by iTim314** [comment]
Correct. I severed the HK pairing and am only using the plugin.

**Comment by bwp91** [comment]
Have sent a couple of requests out to users of old issues to see if anyone has any insight 🙂

**Comment by iTim314** [comment]
I appreciate it. If I had any Node experience I'd pull this down and take a crack at it. Maybe over the next month or so I can fiddle with it in my spare time.

**Comment by bwp91** [comment]
the plugin is just javascript. happy to help you setting up 'locally' if helpful

**Comment by ekhalil-SE** [comment]
I have similar issue. Please see attached screenshot.
![image](https://github.com/bwp91/homebridge-meross/assets/68658490/bbbd2514-a908-413c-ac16-bffdcec5110a)
