### ISSUE TITLE
Plugin disabling itself when used with Meross mss110 devices.

### ISSUE THREAD

**Issue by bennettbri62** [donavanbecker/homebridge-meross#518]
### What issue do you have? Please be as thorough and explicit as possible.
* Just upgraded plugin to 9.0.3 and getting errors that disable this plugin:
...
[4/20/2023, 11:20:31 AM] [Meross] Disabling cloud client as invalid device list received -
...
 at default.getDevices (file:///var/lib/homebridge/node_modules/homebridge-meross/lib/connection/http.js:144:15).
[4/20/2023, 11:20:31 AM] [Meross] ***** Disabling plugin. *****
[4/20/2023, 11:20:31 AM] [Meross] ***** Neither of username and password nor user key has been configured. *****

I looked at the code and it is experiencing this in lib\connection\http.js function async getDevices():
...
      if (
        res.data.info !== 'Success'
        || !hasProperty(res.data, 'data')
        || !Array.isArray(res.data.data)
      ) {
        throw new Error(`${platformLang.invalidDevices} - ${JSON.stringify(res.data)}`);
      }
...

I also get a copy of the response and I can see that info is present but blank value:
...
{
   "apiStatus":0,
   "sysStatus":0,
   "info":"",
   "timestamp":1682007631,
   "data":[
      {
...
and the response also contains what appears to be accurate details of my devices.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
* I use Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
* Homebridge: v4.50.2

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* I run homebridge on an Ubuntu 22.04 servers. Node.js/NPM version: [v18.16.0](https://homebridge.io/w/JTKEF)

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
* Started failing on 4/20/2023 but I believe it was failing before I upgraded plugin to 9.0.3 (an attempt to resolve), but sorry I don't have the prior plugin version 

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
* 3 devices: All mss110 smart plugs

### Please paste any relevant logs below.

homebridge log:
[4/20/2023, 11:20:18 AM] [HB Supervisor] OS: Linux 5.15.0-70-generic x64
[4/20/2023, 11:20:18 AM] [HB Supervisor] Node.js v18.16.0 /opt/homebridge/bin/node
[4/20/2023, 11:20:18 AM] [HB Supervisor] Homebridge Path: /var/lib/homebridge/node_modules/homebridge/bin/homebridge
[4/20/2023, 11:20:18 AM] [HB Supervisor] UI Path: /opt/homebridge/lib/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[4/20/2023, 11:20:25 AM] [Homebridge UI] Homebridge Config UI X v4.50.2 is listening on :: port 8581
[4/20/2023, 11:20:26 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[4/20/2023, 11:20:26 AM] [HB Supervisor] Started Homebridge v1.6.0 with PID: 10182
[4/20/2023, 11:20:28 AM] Loaded config.json with 0 accessories and 3 platforms.
[4/20/2023, 11:20:28 AM] Loaded 2 cached accessories from cachedAccessories.
[4/20/2023, 11:20:28 AM] ---
[4/20/2023, 11:20:29 AM] Loaded plugin: homebridge-meross@9.0.3
[4/20/2023, 11:20:29 AM] Registering platform 'homebridge-meross.Meross'
[4/20/2023, 11:20:29 AM] ---
[4/20/2023, 11:20:29 AM] Loaded plugin: homebridge-tplink-smarthome@7.0.1
[4/20/2023, 11:20:29 AM] Registering platform 'homebridge-tplink-smarthome.TplinkSmarthome'
[4/20/2023, 11:20:29 AM] ---
[4/20/2023, 11:20:29 AM] Loading 3 platforms...
[4/20/2023, 11:20:29 AM] [TplinkSmarthome] Initializing TplinkSmarthome platform...
[4/20/2023, 11:20:29 AM] [TplinkSmarthome] homebridge-tplink-smarthome v7.0.1, node v18.16.0, homebridge v1.6.0, api v2.7
[4/20/2023, 11:20:30 AM] [Meross] Initializing Meross platform...
[4/20/2023, 11:20:30 AM] [Meross] Initialising plugin v9.0.3 | System linux | Node v18.16.0 | HB v1.6.0 | HAPNodeJS v0.11.0...
[4/20/2023, 11:20:30 AM] [TplinkSmarthome] Configuring cached accessory: [Front lights] UUID: a88dfd78-56b0-4cbe-ae7d-46ac80dcc9a6 deviceId: 8006FFDCA063E27D6768234860F9392520AD4A86
[4/20/2023, 11:20:30 AM] [TplinkSmarthome] Configuring cached accessory: [Deck lights] UUID: 434c31d0-c3df-4800-8317-151ee5be96f7 deviceId: 80062639E61714EB7D63BB1B66C4C81F206DB4B2
[4/20/2023, 11:20:30 AM] [Meross] Plugin initialised. Setting up accessories....
Setup Payload:
X-HM://0023TG19PWIZY
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:

    ┌────────────┐
    │ 210-17-453 │
    └────────────┘

[4/20/2023, 11:20:30 AM] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 1CC1) is running on port 51055.
[4/20/2023, 11:20:30 AM] [TplinkSmarthome] Device First Online: [Front lights] plug [8006FFDCA063E27D6768234860F9392520AD4A86] 192.168.1.27 9999
[4/20/2023, 11:20:30 AM] [TplinkSmarthome] Adding: [Front lights] plug [8006FFDCA063E27D6768234860F9392520AD4A86]
[4/20/2023, 11:20:30 AM] [TplinkSmarthome] Device First Online: [Deck lights] plug [80062639E61714EB7D63BB1B66C4C81F206DB4B2] 192.168.1.29 9999
[4/20/2023, 11:20:30 AM] [TplinkSmarthome] Adding: [Deck lights] plug [80062639E61714EB7D63BB1B66C4C81F206DB4B2]
[4/20/2023, 11:20:31 AM] [Meross] Disabling cloud client as invalid device list received - {"apiStatus":0,"sysStatus":0,"info":"","timestamp":1682007631,"data":[{"uuid":"2104306003077351855648e1e96fae0a","onlineStatus":1,"devName":"Family room lamp","devIconId":"device001","bindTime":1680878582,"deviceType":"mss110","subType":"us","channels":[{}],"region":"us","fmwareVersion":"7.3.17","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"domain":"mqtt-us-2.meross.com","reservedDomain":"mqtt-us-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2104307238802851855648e1e96fe578","onlineStatus":1,"devName":"Master bedroom lamp","devIconId":"device001","bindTime":1676752174,"deviceType":"mss110","subType":"us","channels":[{}],"region":"us","fmwareVersion":"7.3.17","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"domain":"mqtt-us-2.meross.com","reservedDomain":"mqtt-us-2.meross.com","cluster":2,"hardwareCapabilities":[]},{"uuid":"2104307640215151855648e1e96fb01d","onlineStatus":1,"devName":"Living room lamp","devIconId":"device001","bindTime":1676748032,"deviceType":"mss110","subType":"us","channels":[{}],"region":"us","fmwareVersion":"7.3.17","hdwareVersion":"7.0.0","userDevIcon":"","iconType":1,"domain":"mqtt-us-2.meross.com","reservedDomain":"mqtt-us-2.meross.com","cluster":2,"hardwareCapabilities":[]}]} at default.getDevices (file:///var/lib/homebridge/node_modules/homebridge-meross/lib/connection/http.js:144:15).
[4/20/2023, 11:20:31 AM] [Meross] ***** Disabling plugin. *****
[4/20/2023, 11:20:31 AM] [Meross] ***** Neither of username and password nor user key has been configured. *****

```

```

**Comment by bennettbri62** [comment]
Duplicate of https://github.com/bwp91/homebridge-meross/issues/517

**Comment by bennettbri62** [comment]
Duplicate of https://github.com/bwp91/homebridge-meross/issues/517
