### ISSUE TITLE
MSS110 sending update failed as socket hang up at Function.AxiosError.from

### ISSUE THREAD

**Issue by mruwzum** [donavanbecker/homebridge-meross#576]
Axios Socket fails when switching MSS110 device.
--
<br class="Apple-interchange-newline">
### Details of your setup.

* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1 Homebridge UI-X 

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.8.3 (HAP v0.12.2)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi -  Node.js version  v20.15.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
v10.4.0 

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
MSS110

### Please paste any relevant logs below.
`[28/06/2024, 12:18:12] [Meross] [MSS110_DEVICE_NAME] sending update failed as socket hang up at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:89:14).`

```

```

**Comment by mozilla33** [comment]
Having the same error from MSG200 garage opener. Using 
HomeBridge UI on HomeBridge v1.6, RPI Raspbian GNU/Linux Bullseye (11), Node v20.11.0 and Meross plug-in v10.4.0

`[Meross][Smart Garage Door Opener] sending update failed as socket hang up at Function.AxiosError.from (file:///var/lib/homebridge/node_modules/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:89:14)`

**Comment by merv2k4** [comment]
Having the same error too using MSS110 homekit native

[11/23/2024, 11:56:58 PM] [Meross] [MSS110_DEVICE_NAME] sending update failed as socket hang up at Function.AxiosError.from (file:///homebridge/node_modules/@homebridge-plugins/homebridge-meross/node_modules/axios/lib/core/AxiosError.js:92:14).

**Comment by Sereniity** [comment]
Same issue here, overnight all the MSS110 plugs are offline in the plugin, they work fine in the Meross app but not HomeKit, they’re set up as local devices too with no login provided.

The plugs don’t show as no response they show as normal they just don’t do anything. Nothing has changed, no updates no IP changes.

The plugs I have aren’t HomeKit compatible natively if that adds anything useful as above [merv2k4](https://github.com/merv2k4) said theirs were. 

Meross plugin: v10.8.1
Home bridge: v1.8.5
Node.js Version: v22.12.0

```
[12/15/2024, 9:20:11 AM] [Meross] [Bedro
om Lamp] sending update
failed as socket
hang up at Function.AxiosError.from (fi
le:///homebridge/node_modules/homebridge
-meross/node
modules/axios/lib/core/Axio
sError. js: 92:14).
```
