### ISSUE TITLE
MTS200 - Offline

### ISSUE THREAD

**Issue by Anqui3tas** [donavanbecker/homebridge-meross#628]
### What issue do you have? Please be as thorough and explicit as possible.
MTS200 shows as offline, (previously setup with username/password to obtain UUID)
UUID copied from plugin
IP is static at router level (no WAN access)
firmware copied from meross app
- 2 other devices (powerstrips) work correctly (also blocked from WAN access)
- Can still interact with thermostat via meross app
- No WAN access is why i'm using this plugin, as directly with HomeKit it would be unreachable after a few days with no internet access. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS?
* Homebridge via Synology Docker

* Which version of Homebridge/HOOBS do you have?
homebridge UI: Installed: v4.60.1
homebridge: Installed: v2.0.0-beta.22

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Node.js Version	v20.18.0

* Which version of this plugin (homebridge-meross) do you have? Has the issue started since upgrading from a previous version?
*New to plugin - v10.7.1-beta.3

* Which Meross devices do you have that are causing issues? Please include product models if applicable.
* MTS200 - Thermostat - Other Accessories working fine

### Please paste any relevant logs below.

```
[10/8/2024, 1:10:37 PM] [Meross] [Livingroom Thermostat] sending update failed as Cannot read properties of undefined (reading 'add') at default.internalStateUpdate (file:///homebridge/node_modules/homebridge-meross/lib/device/thermostat.js:142:24).
[10/8/2024, 1:10:39 PM] [Meross] [Livingroom Thermostat] sending update failed as Cannot read properties of undefined (reading 'add') at default.internalStateUpdate (file:///homebridge/node_modules/homebridge-meross/lib/device/thermostat.js:142:24).

```

**Comment by bartos-martin** [comment]
Quick question - what is the firmware version of your MTS200 ?
There is a new (firmware) update available for a couple of days and i'm wondering whether that might have caused this issue.

**Comment by Anqui3tas** [comment]
7.6.7.1.2.1 is the firmwareMeross products also seem to now have a phone home/disable feature. When blocked from WAN via firewall, they will stop working in HomeKit (unreachable) after 3-4 days. Even when allowing access to only the time servers (to make sure it wasn’t a time sync issue)Not sure if this plugin can resolve that (as that was my goal with the plugin, to force local only communication)On Nov 8, 2024, at 12:15 AM, Baro ***@***.***> wrote:﻿
Quick question - what is the firmware version of your MTS200 ?
There is a new update available for a couple of days and i'm wondering whether that might have caused this issue.
