### ISSUE TITLE
Does this plugin support the Meross MSS560 US dimmer switch?

### ISSUE THREAD

**Issue by wnaylor** [donavanbecker/homebridge-meross#7]
I tried setting up the Meross plugin using the Charles app but I can't get Homebridge to recognize the MSS560 US switch. Here is what the config-ui-x logs say: 

[Pantry Switch] Failed to POST to the Meross Plug: Error: Invalid URI "192.168.1.87/config"
    at Request.init (/usr/local/lib/node_modules/homebridge-meross/node_modules/request/request.js:273:31)
    at new Request (/usr/local/lib/node_modules/homebridge-meross/node_modules/request/request.js:127:8)
    at request (/usr/local/lib/node_modules/homebridge-meross/node_modules/request/index.js:53:10)
    at /usr/local/lib/node_modules/homebridge-meross/index.js:9:5
    at new Promise (<anonymous>)
    at doRequest (/usr/local/lib/node_modules/homebridge-meross/index.js:8:10)
    at MerossPlug.getOnCharacteristicHandler (/usr/local/lib/node_modules/homebridge-meross/index.js:175:24)
    at Characteristic.On.emit (events.js:223:5)
    at Characteristic.On.Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
    at HAPServer.emit (events.js:223:5)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:223:5)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
[1/31/2020, 2:53:42 PM] [Pantry Switch] Retrieved status unsuccessfully.
[1/31/2020, 2:53:42 PM] [Pantry Switch] calling getOnCharacteristicHandler: false

**Comment by donavanbecker** [comment]
If you can create a pull request for it. I can push it. I am just maintaining this Repo.

**Comment by dylanfrankcom** [comment]
Hi @wnaylor, the payload could be different as it is a dimmer switch and I haven't had any experience with it. However, the error message you are getting is similar to [this issue](https://github.com/donavanbecker/homebridge-meross/issues/20). 

Could you please check your config file and attempt this [possible solution](https://github.com/donavanbecker/homebridge-meross/issues/20#issuecomment-614715442) and report back?

**Comment by donavanbecker** [comment]
Just released [Version 1.1.0](https://github.com/donavanbecker/homebridge-meross/releases/tag/v1.1.0), if you want to give it a try.
